### ISSUE TITLE
Training / Transfer Learning

### ISSUE THREAD

**Issue by egemenertugrul** [kaiidams/YamNetUnityDemo#10]
Hi, 

I'd like to know the possible steps to take to train a new model with a different number of classes.

Do you have the modified Tensorflow code (i.e., where yamnet does not perform Log Mel Spectrogram within the ML model) for training a custom model, or did you remove the layers from the existing pre-trained model?

Thank you.

**Comment by kaiidams** [comment]
TensorFlow has a tutorial how to do transfer learning with YAMNet https://www.tensorflow.org/tutorials/audio/transfer_learning_audio.

I used this code https://github.com/tensorflow/models/tree/master/research/audioset/yamnet and removed log mel spectrogram as ONNX didn't support STFT operation. I don't have the modified code any more, but I don't think it was a big modification.

**Comment by egemenertugrul** [comment]
I understand. Thank you for the help!
