### ISSUE TITLE
MFCC or Mel Spectrogram?

### ISSUE THREAD

**Issue by egemenertugrul** [kaiidams/YamNetUnityDemo#9]
Hi, thank you for sharing this project. 

I looked into the code and the .onnx model. The input of yamnet.onnx model says `mfcc`, whereas the C# code seems to extract Mel Spectrogram features (due to the naming of the methods). 

Which one is it that the C# code calculates?

**Comment by kaiidams** [comment]
Thank you for correction. It should calculate log mel spectrogram. Input name of `yamnet.onnx` is wrong.

**Comment by egemenertugrul** [comment]
Understood, thank you!
